### ISSUE TITLE
cmsis_version.h outdated

### ISSUE THREAD

**Issue by KnoerleMan** [STMicroelectronics/cmsis-core#3]
It seems like there are outdated files which are not on the same level as the files in the repository of ARM.

At least the 'cmsis_version.h' file is:
https://github.com/STMicroelectronics/cmsis_core/blob/96d6da4e252b06dcfdc041e7df23e86161c33007/Core/Include/cmsis_version.h#L36

Reference from ARM repo (correct version number):
https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/Core/Include/cmsis_version.h

Please fix this. Thanks.

**Comment by KnoerleMan** [comment]
Furthermore the [Release Notes of the Cube repository](https://htmlpreview.github.io/?https://github.com/STMicroelectronics/STM32CubeH7/blob/master/Release_Notes.html) also list an invalid version number of "included" cmsis core:
![image](https://user-images.githubusercontent.com/55956669/216947228-cb5f5377-9bb4-45f3-b14f-5b038ad975dd.png)

Version 5.6.0 was released in December 2020 and the latest Cube release still uses version 5.3.0 but lists 5.6.0 as included.
You might want to think about using submodules or something similar to keep the bundling repository (Cube) on track.
There are probably more inconsistencies.

**Comment by TOUNSTM** [comment]
Hello @KnoerleMan,

Thank you for your report.  Actually this version v5.6.0 corresponds to `CMSIS` component that includes sub-components such as `CMSIS-Core(M)`, `DSP`, `NN`..

The sub-component versions are different from top `CMSIS` version. So there is no problem in our CMSIS version. Please check this [link](https://github.com/ARM-software/CMSIS_5/blob/5.6.0/CMSIS/Core/Include/cmsis_version.h) to ensure that our drivers are align with ARM's drivers.

However, to avoid any misunderstood, we will update our STM32CubeFW Release note to refer to `CMSIS` instead of `Cortex-M CMSIS`.

This point has been discussed and fixed internally, before we receive your request. The fix will be available soon hopefully.

With Regards,

**Comment by KnoerleMan** [comment]
All right, thank you for the clarification.

Best regards!
