### ISSUE TITLE
Branch organisation and relation to ARM's CMSIS v5 repo

### ISSUE THREAD

**Issue by vincent-chtln** [STMicroelectronics/cmsis-core#4]
Hi ST team,

I was wondering about the relation between this repository and ARM's [official CMSIS v5 repository](https://github.com/ARM-software/CMSIS_5) (lets call it the *base repository*). As far as I understand it, this should be a copy of the `CMSIS` folder from *base repository*, but there are missing files and folders. How do you choose which files to copy here and which not to copy ?

Moreover, there are currently 6 branches in this repository: 1 `master` + 5 branches targetting a specific Cortex-M architecture. What is the difference between these dedicated branches, the `master` branch, and the `develop` branches in the *base repository*. Again, dedicated branches miss files that are present in the `master` branch. How to you choose which files to remove from dedicated branches ?

In the future, do you plan to switch to newer versions of CMSIS v5, or even switch to CMSIS v6 (maybe in `cmsis_core_6` repo) ? It has been 5 years since the 5.6.0 release.

Finally, my team is starting a new project on STM32F4 chips and we would like to submodule git repositories for our components. HAL and CMSIS device will be taken from your git repositories, but should we target this repository over the *base repository* for CMSIS core ?

Thanks !

**Comment by ALABSTM** [comment]
Hi @vincent-chtln,

Thank you for these questions. Please find my answers below:
* To be more specific, this folder is a **subset** of the [CMSIS_5/CMSIS](https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS) folder. Some subfolders like `./CMSIS/DAP` or `./CMSIS/DoxyGen` are not copied as not used in our STM32Cube firmware. Another typical example is the `./CMSIS/Driver` subfolder, replaced by our [drivers](https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer/blob/master/README.md#stm32cube-hal-drivers) (placed elsewhere in the folder tree).
* Regarding the branches other than the main one, like `cm0` and `cm33`, each one contains a **subset** of the main branch's. This is to offer **size-optimized** alternatives.
  * This is mainly about the [./DSP/Lib](https://github.com/STMicroelectronics/cmsis_core/tree/master/DSP/Lib) subfolder, the **most voluminous**. The one on the main branch contains precompiled libraries for all supported cores while the one on the `cm4` branch, for instance, only contains the precompiled libraries for the CM4 core.
  * Note also that the `./Core_A` subfolder is not present on any of the `cmx` branches as applicable to Cortex-A cores not to Cortex-M ones.
* We already upgraded to version 5.9.0 of the CMSIS core but only for some firmware like [STM32CubeC0](https://github.com/STMicroelectronics/STM32CubeC0) or [STM32CubeH5](https://github.com/STMicroelectronics/STM32CubeH5). This repository will be updated accordingly 😃.
* For the needs of your project, I would suggest the following:
  * target this repository, mainly the `cm4` branch, instead of the *base repository*,
  * consider keeping only the [./Include](https://github.com/STMicroelectronics/cmsis_core/tree/cm4/Include) subfolder to reduce the size of your project's repository if other subfolders like `NN` or `DSP` are not needed,
  * if you intend to "submodule" the [cmsis_device_f4](https://github.com/STMicroelectronics/cmsis_device_f4) repository under path `./Device/ST/STM32F4xx`, you may not be able to "submodule" this one as the former should be placed inside the latter (provided you keep the same folder tree as the STM32CubeF4 firmware) and such **nested** submodules are not possible to implement, as far as I know.

I hope this helps. Do not hesitate otherwise and best of luck for your project.

With regards,

**Comment by ALABSTM** [comment]
Hi @vincent-chtln,

Version **5.9.0** of the CMSIS Core provided by *STMicroelectronics* has just been published on this repository. Please allow me to close this thread.

With regards,

**Comment by vincent-chtln** [comment]
Hi @ALABSTM,

Thank you for the detailled information !

As you suggested we will target the `m4` branch to reduce package size (precisely the `v5.6.0_cm4` tag for easier version control).

Since we can obiously not place [cmsis_device_f4](https://github.com/STMicroelectronics/cmsis_device_f4) repository inside another git submodule, we created an `ARM/CMSIS_v5` folder for [cmsis-core](https://github.com/STMicroelectronics/cmsis_core) module and a `ST/Drivers/CMSIS/Device/ST/STM32F4xx` folder for device specific implementation (this architecture mirrors the one in Cube packages), thus splitting submodules according to the external vendor.

We will keep track of the Cube packages' evolution and upgrade to another CMSIS version if needed.

Kind regards,
