### ISSUE TITLE
CMSIS 5.9.0 Release missing precompiled Libs

### ISSUE THREAD

**Issue by mmarciniewski** [STMicroelectronics/cmsis-core#5]
Hi,

With latest CMSIS 5.9.0 release,  the precompiled Libs from the DSP/Libs folder have been removed. Is this intentional? Their presence simplified development by removing an additional step.

Thanks!

**Comment by ALABSTM** [comment]
Hi @mmarciniewski,

Yes, this is intentional. Actually, this repository is based on Arm's [CMSIS_5](https://github.com/ARM-software/CMSIS_5). Starting from release [5.8.0](https://github.com/ARM-software/CMSIS_5/releases/tag/5.8.0), Arm removed these precompiled libraries, as you can see on the screenshot below from their release note.

![image](https://github.com/STMicroelectronics/cmsis_core/assets/46019491/3a82dfd9-cbff-4f33-b4fd-c5c4f533596a)

With regards,

**Comment by mmarciniewski** [comment]
Well that is unfortunate.

Thank you for the reply @ALABSTM.
